spring.application.name=smart-learning-platform

spring.datasource.url=jdbc:postgresql://localhost:5433/Smart-Learning-Platform
spring.datasource.username=postgres
spring.datasource.password=milan@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.banner-mode=off
logging.level.root=INFO


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=milankothiya08@gmail.com
spring.mail.password=hxsr fowc jbhk ytww
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=dk6zhfuzk
cloudinary.api-key=252216813328546
cloudinary.api-secret=GisyDGsgrSN4kAcrJRj4iCOnnvQ


media.image.max-size=5MB
media.video.max-size=500MB
media.pdf.max-size=20MB
spring.servlet.multipart.enabled=true

