spring.application.name=${APPLICATION_NAME:smart-learning-platform}

spring.datasource.url=jdbc:postgresql://localhost:5433/Smart-Learning-Platform
spring.datasource.username=postgres
spring.datasource.password=milan@123

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.banner-mode=off
#logging.level.root=warn

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:hetfaldu0507@gmail.com}
spring.mail.password=${MAIL_PASSWORD:hpooofpgfhleaafo}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}

# ----------------------JWT----------------------------------------

jwt.secret=${JWT_SECRET:oytjigdfsagbxzmmdbwytwqiekrnrgthcmsddliei}
jwt.token.expiration.time.micro.seconds=${JWT_TOKEN_EXPIRATION_TIME_MICRO_SECONDS:300000}
jwt.header=${JWT_HEADER:Authorization}

# ----------------------Password reset----------------------------------------
password.reset.token.expiration.time.micro.seconds=${PASSWORD_RESET_TOKEN_EXPIRATION_TIME_MICRO_SECONDS:60000}
otp.change.password.expiry.seconds=${OTP_CHANGE_PASSWORD_EXPIRY_SECONDS:300}
otp.change.password.resend.seconds=${OTP_CHANGE_PASSWORD_RESEND_SECONDS:30}

# ----------------------Email otp----------------------------------------

otp.email.expiry.time.seconds=${OTP_EMAIL_EXPIRY_TIME_SECONDS:300}
otp.email.resend.seconds=${OTP_EMAIL_RESEND_SECONDS:30}

# ----------------------Phone otp----------------------------------------

otp.phone.expiry.time.seconds=${OTP_PHONE_EXPIRY_TIME_SECONDS:300}
otp.phone.resend.seconds=${OTP_PHONE_RESEND_SECONDS:30}

# ----------------------Device----------------------------------------

device.id.cookie.name=${DEVICE_ID_COOKIE_NAME:device_id}
device.id.cookie.http_only=${DEVICE_ID_COOKIE_HTTP_ONLY:true}
device.id.cookie.secure=${DEVICE_ID_COOKIE_SECURE:true}
device.id.cookie.path=${DEVICE_ID_COOKIE_PATH:/}
device.id.cookie.same.site=${DEVICE_ID_COOKIE_SAME_SITE:strict}
device.id.cookie.expiry.seconds=${DEVICE_ID_COOKIE_expiry_seconds:31536000}

# ----------------------Useragent----------------------------------------

user.agent.header=${USER_AGENT_HEADER:User-Agent}

# ----------------------Session----------------------------------------

session.expiry.time.seconds=${SESSION_EXPIRY_TIME_SECONDS:604800}
session.client.ip.header=${SESSION_CLIENT_IP_HEADER:X-Forwarded-For}

# Tell Flyway the DB already exists at baseline version
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1


redis.rate_limit.database.address=${REDIS_RATE_LIMIT_DATABASE_ADDRESS:redis://localhost:6379}