spring.application.name=smart-learning-platform
spring.datasource.url=jdbc:postgresql://localhost:5433/smart_learning_platform
spring.datasource.username=postgres
spring.datasource.password=Hetfaldu@1
spring.jpa.hibernate.ddl-auto=create
spring.main.banner-mode=off
spring.jpa.show-sql=true
logging.level.root=warn