package com.fm.smartlearningplatform.model.lesson;

import com.fm.smartlearningplatform.model.user.Language;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "lesson_caption",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_lesson_language_caption",
                        columnNames = {"lesson_id", "language_id"}
                )
        })
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class LessonCaption {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="lesson_id",nullable = false)
    private Lesson lesson;

    @ManyToOne
    @JoinColumn(name="language_id",nullable = false)
    private Language language;

    @Column(name="caption_url",nullable = false)
    private String captionUrl;

    @ManyToOne
    @JoinColumn(name="caption_type",nullable = false)
    private CaptionType captionType;

    @Column(name="is_auto_generated")
    private boolean isAutoGenerated;

    @CreationTimestamp
    @Column(name="created_at",updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name="updated_at")
    private LocalDateTime updatedAt;
}