spring.application.name=smart-learning-platform

spring.datasource.url=jdbc:postgresql://localhost:5433/smart_learning_platform
spring.datasource.username=postgres
spring.datasource.password=Hetfaldu@1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.banner-mode=off
#logging.level.root=warn

spring.security.user.name=het
spring.security.user.password=het

#server.servlet.session.timeout=30s

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hetfaldu0507@gmail.com
spring.mail.password=hpooofpgfhleaafo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true