spring.application.name=smart-learning-platform

spring.datasource.url=jdbc:postgresql://localhost:5433/Smart-Learning-Platform
spring.datasource.username=postgres
spring.datasource.password=milan@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.banner-mode=off
logging.level.root=warn


spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET

spring.security.oauth2.client.registration.google.scope=email,profile



spring.security.oauth2.client.registration.github.client-id=Ov23lispjnE48MAUqafL

spring.security.oauth2.client.registration.github.client-secret=9d1208b2a0e8d925597f0b486303b220c09fd79d